name: setup-nasm

on:
  pull_request:
  push:
    branches:
      - master
      - release/*
      - wip/rpm
  schedule:
    - cron:  '0 6 * * 1'

jobs:
  test-default:
    name: default
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        version: [2.15.05]
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Download Internet
        run: npm install
      - name: Install NASM
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Verify NASM
        shell: bash
        run: |
          [[ "$(nasm -version)" =~ "NASM version ${{ matrix.version }}" ]]
