name: setup-nasm

on:
  pull_request:
  push:
    branches:
      - master
      - release/*
      - wip/rpm
  schedule:
    - cron:  '0 6 * * 1'

jobs:
  test-default:
    name: default
    if: (matrix.os == 'ubuntu-latest') && (matrix.version == '2.15.05')
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        version: [2.15.05, 2.14.02]
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Download Internet
        run: npm install
      - name: Install NASM
        uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Verify NASM
        shell: bash
        run: |
          [[ "$(nasm -version)" =~ "NASM version ${{ matrix.version }}" ]]
  # We currently do not support source builds on Windows,
  # but GitHub Actions strategy.matrix.exclude is current bugged
  # so we have to duplicate the job instead of filtering out :(
  test-source:
    name: source-only
    if: false
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        version: [2.15.05, 2.14.02]
    steps:
      - name: Check out source code
        uses: actions/checkout@v1
      - name: Download Internet
        run: npm install
      - name: Install NASM
        uses: ./
        with:
          version: ${{ matrix.version }}
          from-source: true
      - name: Verify NASM
        shell: bash
        run: |
          [[ "$(nasm -version)" =~ "NASM version ${{ matrix.version }}" ]]
